stages:
- stage: PPE
  jobs:
  - deployment: DeployPPE
    environment: Nikhil-Env08
    pool: 'Hosted'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'
